In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("../bluestock_mf.db")

In [3]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

               name
0          dim_fund
1          fact_nav
2  fact_transaction
3  fact_performance

In [4]:
query = """
SELECT scheme_name,
       aum_crore
FROM fact_performance
ORDER BY aum_crore DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

                                         scheme_name  aum_crore
0  Mirae Asset Emerging Bluechip Fund - Regular -...      49046
1      Kotak Emerging Equity Fund - Regular - Growth      47469
2     Nippon India Small Cap Fund - Regular - Growth      43630
3         DSP Top 100 Equity Fund - Regular - Growth      41828
4                UTI Mid Cap Fund - Regular - Growth      41728

In [5]:
query = """
SELECT amfi_code,
       ROUND(AVG(nav),2) AS avg_nav
FROM fact_nav
GROUP BY amfi_code
ORDER BY avg_nav DESC;
"""

pd.read_sql(query, conn)

    amfi_code  avg_nav
0      120844  3705.88
1      125497   797.45
2      100016   566.19
3      149322   439.18
4      101206   435.98
5      101208   358.39
6      120841   355.08
7      120507   334.08
8      120505   284.00
9      120506   274.32
10     102887   249.53
11     118635   228.25
12     100033   190.83
13     119598   180.31
14     149323   151.49
15     149324   148.21
16     148568   147.76
17     125498   138.21
18     102886   137.10
19     148567   136.48
20     102885   128.49
21     119094   121.44
22     119599   108.58
23     118634   102.90
24     119552   100.75
25     120504    99.94
26     120843    97.82
27     120503    89.68
28     119551    78.85
29     119095    75.65
30     118632    73.63
31     120842    67.66
32     118633    62.12
33     101207    58.96
34     148569    54.52
35     119120    48.57
36     119092    48.02
37     119093    43.77
38     118636    33.62
39     100025    29.10

In [6]:
query = """
SELECT transaction_type,
       COUNT(*) AS total_transactions
FROM fact_transaction
GROUP BY transaction_type;
"""

pd.read_sql(query, conn)

  transaction_type  total_transactions
0          Lumpsum                8095
1       Redemption                4967
2              Sip               19716

In [7]:
query = """
SELECT state,
       ROUND(SUM(amount_inr),2) AS total_amount
FROM fact_transaction
GROUP BY state
ORDER BY total_amount DESC;
"""

pd.read_sql(query, conn)

             state  total_amount
0           Punjab   315780459.0
1       Tamil Nadu   315177237.0
2   Madhya Pradesh   308312493.0
3        Rajasthan   298645822.0
4          Gujarat   298358940.0
5      West Bengal   297182514.0
6        Telangana   290219284.0
7            Delhi   289633404.0
8    Uttar Pradesh   285368873.0
9          Haryana   279634354.0
10       Karnataka   273753570.0
11     Maharashtra   269513480.0

In [8]:
query = """
SELECT investor_id,
       ROUND(SUM(amount_inr),2) AS invested_amount
FROM fact_transaction
GROUP BY investor_id
ORDER BY invested_amount DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  investor_id  invested_amount
0   INV003288        3480685.0
1   INV001999        3179916.0
2   INV004605        2882975.0
3   INV000477        2846388.0
4   INV001692        2751086.0
5   INV002039        2713616.0
6   INV001771        2695710.0
7   INV002553        2668557.0
8   INV002707        2651584.0
9   INV002245        2623784.0

In [9]:
query = """
SELECT kyc_status,
       COUNT(*) AS total
FROM fact_transaction
GROUP BY kyc_status;
"""

pd.read_sql(query, conn)

  kyc_status  total
0    PENDING   2632
1   VERIFIED  30146

In [10]:
query = """
SELECT scheme_name,
       sharpe_ratio
FROM fact_performance
ORDER BY sharpe_ratio DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                         scheme_name  sharpe_ratio
0           ICICI Pru Liquid Fund - Regular - Growth          7.68
1               Kotak Liquid Fund - Regular - Growth          6.18
2                ABSL Liquid Fund - Regular - Growth          5.14
3       HDFC Short Term Debt Fund - Regular - Growth          1.84
4       SBI Magnum Gilt Fund - Regular Plan - Growth          1.52
5  Nippon India Gilt Securities Fund - Regular - ...          1.33
6          HDFC Top 100 Fund - Regular Plan - Growth          1.06
7      Mirae Asset Large Cap Fund - Regular - Growth          1.06
8          ICICI Pru Bluechip Fund - Direct - Growth          1.03
9     Nippon India Large Cap Fund - Regular - Growth          1.00

In [11]:
query = """
SELECT scheme_name,
       return_3yr_pct
FROM fact_performance
ORDER BY return_3yr_pct DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                         scheme_name  return_3yr_pct
0         SBI Small Cap Fund - Regular Plan - Growth           23.39
1          SBI Small Cap Fund - Direct Plan - Growth           23.14
2             ABSL Small Cap Fund - Regular - Growth           22.38
3             Axis Small Cap Fund - Regular - Growth           20.98
4     Nippon India Small Cap Fund - Regular - Growth           20.15
5              DSP Small Cap Fund - Regular - Growth           20.08
6      Kotak Emerging Equity Fund - Regular - Growth           18.23
7           ICICI Pru Midcap Fund - Regular - Growth           18.08
8                 DSP Midcap Fund - Regular - Growth           17.16
9  HDFC Mid-Cap Opportunities Fund - Regular - Gr...           16.58

In [12]:
query = """
SELECT
ROUND(AVG(alpha),4) AS avg_alpha,
ROUND(AVG(beta),4) AS avg_beta
FROM fact_performance;
"""

pd.read_sql(query, conn)

   avg_alpha  avg_beta
0     1.2535    0.8732

In [13]:
query = """
SELECT category,
       COUNT(*) AS fund_count
FROM dim_fund
GROUP BY category
ORDER BY fund_count DESC;
"""

pd.read_sql(query, conn)

  category  fund_count
0   Equity          34
1     Debt           6

In [14]:
conn.close()
print("Connection Closed")

Connection Closed